### ISSUE TITLE
How to define the length of predict seq in this project?

### ISSUE THREAD

**Issue by dandeperson** [zshicode/MambaStock#2]
Thanks

**Comment by zshicode** [comment]
We adopt an argument parser by package argparse in Python, and the options for running code are defined as follow:
```
parser.add_argument('--n-test', type=int, default=300,
                    help='Size of test set')
```                

This line of code sets the default length of predicted seq as 300, or you can use
```
python main.py --n-test 300
```
to set the length of predicted seq.

**Comment by dandeperson** [comment]
Thank you for your answer, maybe I didn't express this clearly. 
To put it this way, are you training with x1,x2,... ,xn as input, y1,y2,.... ,yn as the true values for the loss calculation? 
In my understanding, this is not a time series prediction problem, but a fitting. In time series tasks, it is usually known that x1,x2, . .xs, predicting x_s+1, . . x_s+s, where the prediction length is s. 
How to understand this, please?

**Comment by dandeperson** [comment]
As I am new to this field, I may have some misunderstandings. Thank you very much for your valuable reply!
