### ISSUE TITLE
Mamba's features

### ISSUE THREAD

**Issue by brunodifranco** [zshicode/MambaStock#4]
First of all, great work. You're results are amazing and the code is easy to reproduce and read. I'm new to the Mamba architecture, and still have a few questions :D.

I'm really curious regarding the following comment in the closed issue "Data leakage from the future? #3":

"Mamba model only adopts features in previous timestamps for prediction."

Can you point in the Mamba code where this is shown?

This means that if the model is predicting tomorrow's stock return, it's using today's open, low, high and volume features for instance?

**Comment by zshicode** [comment]
The prediction procedure of Mamba model is typically implemented to ensure that no future information is leaked into the current prediction.  Therefore, when predicting tomorrow's stock return, the model indeed uses today's (and earlier) open, low, high, and volume data as features, adhering strictly to a temporal order that prevents lookahead bias.
