### ISSUE TITLE
预测结果之后问题

### ISSUE THREAD

**Issue by zenoda** [zshicode/MambaStock#5]
我测试了一下，虽然从损失上看很理想，但是我观察了一下预测数据和目标数据，发现预测结果与前一天的数据非常接近，也就是说预测结果滞后，误差之所以小，是因为相邻两天股价的变化多数情况下都不会很大，神经网络其实是在投机取巧。如果把这个模型应用于实际交易，会发现每次预测结果都与前一天收盘价接近，这对交易几乎没有任何指导意义。 
当然这个问题并非这个模型的缺陷，事实上我用很多方法都得到了类似的结果。

![image](https://github.com/user-attachments/assets/3424b559-71fc-4ca0-9c73-a2a9d919e732)

**Comment by aixiaodewugege** [comment]
![Image](https://github.com/user-attachments/assets/d98648ac-f521-41e9-9ee1-9e414c182b42)
hahaha，too many people waste their time on these useless method.

**Comment by josephgiting** [comment]
@zenoda @aixiaodewugege Would appreciate if you can elaborate further about your comments please?

I think I spot something which seems to be what you are talking about, but couldn't find out where was the problem. Changing the code to plot without 'time':

`plt.plot(data1, label='Stock Price')
plt.plot(finalpredicted_stock_price, label='Predicted Stock Price')`

would produce the following:

<img width="1433" height="499" alt="Image" src="https://github.com/user-attachments/assets/063d2a62-1ca6-4a15-b7f1-5660072d141d" />

Hope someone can explain the reason for this finding.
Cheers,
